name: Mercury ci

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: ubuntu:rolling
    
    steps:
    - name: update
      run: apt update -y && apt upgrade -y && apt autoremove -y && apt install git git-lfs -y
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: chmod +x make_deb.sh
      run: chmod +x make_deb.sh
    - name: build deb
      run: ./make_deb.sh
      continue-on-error: true  # This line ensures that the workflow continues even if this step fails
    - name: ls
      run: ls -a
